[package]
name = "pql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dropshot = "0.6.0"
jsonschema = "0.13.3"
serde = "1.0.133"
http = "0.2.6"
schemars = "0.8.8"
tokio = "1.15.0"
